/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyStencilElement {
    }
}
declare global {
    interface HTMLMyStencilElementElement extends Components.MyStencilElement, HTMLStencilElement {
    }
    var HTMLMyStencilElementElement: {
        prototype: HTMLMyStencilElementElement;
        new (): HTMLMyStencilElementElement;
    };
    interface HTMLElementTagNameMap {
        "my-stencil-element": HTMLMyStencilElementElement;
    }
}
declare namespace LocalJSX {
    interface MyStencilElement {
    }
    interface IntrinsicElements {
        "my-stencil-element": MyStencilElement;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-stencil-element": LocalJSX.MyStencilElement & JSXBase.HTMLAttributes<HTMLMyStencilElementElement>;
        }
    }
}
